### PR TITLE
update README.md and _sidebar.md

### PR DESCRIPTION
**Pull request by Comet959**

### CODE REVIEW

**Review by caodg — CHANGES_REQUESTED** [review]
pls merge updates and resolve conflicts.

**Review by caodg — COMMENTED** [review]
and you should work on a branch such as dev, not main, in case your pr is under a long reviewing process, however you need also work on another new feature at the same time.

**Comment by Comet959** [comment]
> conflicts

No pb, conflict has been resolved now, and I'll work on my own branch soon.

**Comment by Comet959** [comment]
> and you should work on a branch such as dev, not main, in case your pr is under a long reviewing process, however you need also work on another new feature at the same time.

No pb, conflict has been resolved now, and I'll work on my own branch soon.

**Review by caodg — APPROVED** [review]

**Pull request merged**
